// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiDeuMq53e_ZdQhTWVC9kQ34OYmr6LSv8',
    appId: '1:855034559751:web:4bd52f6de9a58aca0e99a2',
    messagingSenderId: '855034559751',
    projectId: 'socialmedieapp-f9efb',
    authDomain: 'socialmedieapp-f9efb.firebaseapp.com',
    storageBucket: 'socialmedieapp-f9efb.appspot.com',
    measurementId: 'G-B3PRER0BE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhT4-7ruC4rgViP8ONBegf7I2v7AX8i0',
    appId: '1:855034559751:android:4b1fe0991508a2250e99a2',
    messagingSenderId: '855034559751',
    projectId: 'socialmedieapp-f9efb',
    storageBucket: 'socialmedieapp-f9efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZDDjGaiGlJM3ifnTDJHOiUwY7Q3QRVY',
    appId: '1:855034559751:ios:b074132ab64ac2a70e99a2',
    messagingSenderId: '855034559751',
    projectId: 'socialmedieapp-f9efb',
    storageBucket: 'socialmedieapp-f9efb.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZDDjGaiGlJM3ifnTDJHOiUwY7Q3QRVY',
    appId: '1:855034559751:ios:b074132ab64ac2a70e99a2',
    messagingSenderId: '855034559751',
    projectId: 'socialmedieapp-f9efb',
    storageBucket: 'socialmedieapp-f9efb.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiDeuMq53e_ZdQhTWVC9kQ34OYmr6LSv8',
    appId: '1:855034559751:web:7b82dbdf2de92dcb0e99a2',
    messagingSenderId: '855034559751',
    projectId: 'socialmedieapp-f9efb',
    authDomain: 'socialmedieapp-f9efb.firebaseapp.com',
    storageBucket: 'socialmedieapp-f9efb.appspot.com',
    measurementId: 'G-Z60H9BQNHB',
  );
}
